name: Main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SOLUTION_FILE_PATH: TestProject/TestProject.sln
  BUILD_CONFIGURATION: Release
  PLATFORM: x64
  EXE_BUILD_LOCATION: TestProject/x64/Release/TestProject.exe
  EXE_NAME: TestProject.exe

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /property:Platform=${{env.PLATFORM}} ${{env.SOLUTION_FILE_PATH}}

    - name: Move exe
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: move ${{env.EXE_BUILD_LOCATION}} .

    - name: Execute
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./${{env.EXE_NAME}} >Output.txt

    - name: Check output
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: git diff --no-index Output.txt ExpectedOutput.txt
